/* ============================================================
   BANQUE DE QUESTIONS — bilingue FR / EN
   Chaque thème a un pool de questions. Le quiz en pioche
   aléatoirement le nombre demandé (10/20/50/100, avec
   répétition possible si le pool est plus petit que la demande).
   ============================================================ */

var THEMES = [
  { id: 'culture', icon: 'book',     color: '#D9622B' },
  { id: 'sport',   icon: 'ball',     color: '#4A7856' },
  { id: 'cinema',  icon: 'clap',     color: '#2B4570' },
  { id: 'geo',     icon: 'globe',    color: '#E0A93E' },
  { id: 'music',   icon: 'note',     color: '#A33B3B' },
  { id: 'history', icon: 'scroll',   color: '#6B5435' },
  { id: 'science', icon: 'flask',    color: '#3B7A7A' },
  { id: 'games',   icon: 'pad',      color: '#7A4F9E' },
  { id: 'series',  icon: 'tv',       color: '#B8552F' },
  { id: 'animals', icon: 'paw',      color: '#5A7A3B' }
];

var QUESTIONS = {

  fr: {
    culture: [
      { q: "Quelle est la capitale de l'Australie ?", a: ["Sydney","Melbourne","Canberra","Brisbane"], c: 2, info: "Beaucoup pensent que c'est Sydney, mais Canberra est la capitale depuis 1927." },
      { q: "Combien de planètes compte notre système solaire ?", a: ["7","8","9","10"], c: 1, info: "Pluton a été reclassifiée en planète naine en 2006." },
      { q: "Qui a peint la Joconde ?", a: ["Michel-Ange","Raphaël","Léonard de Vinci","Botticelli"], c: 2, info: "Peinte entre 1503 et 1519, elle est exposée au Louvre." },
      { q: "En quelle année a débuté la Première Guerre mondiale ?", a: ["1912","1914","1916","1918"], c: 1, info: "Déclenchée par l'assassinat de l'archiduc François-Ferdinand." },
      { q: "Quel est le symbole chimique de l'or ?", a: ["Ag","Al","Au","Or"], c: 2, info: "Au vient du latin 'Aurum'." },
      { q: "Quel pays a la plus grande superficie du monde ?", a: ["Canada","Chine","USA","Russie"], c: 3, info: "La Russie couvre 17,1 millions de km²." },
      { q: "Combien d'os compte le corps humain adulte ?", a: ["186","206","226","246"], c: 1, info: "Les bébés naissent avec environ 270 os." },
      { q: "Quelle est la langue maternelle la plus parlée ?", a: ["Anglais","Espagnol","Mandarin","Hindi"], c: 2, info: "Le mandarin compte 1,1 milliard de locuteurs natifs." },
      { q: "Qui a formulé la théorie de la relativité ?", a: ["Newton","Tesla","Curie","Einstein"], c: 3, info: "Relativité restreinte en 1905, générale en 1915." },
      { q: "Où se trouve le Machu Picchu ?", a: ["Bolivie","Mexique","Pérou","Colombie"], c: 2, info: "Cité inca à 2430 mètres d'altitude, construite vers 1450." },
      { q: "Quel est le plus petit pays du monde ?", a: ["Monaco","Vatican","Nauru","Malte"], c: 1, info: "Le Vatican mesure environ 0,49 km²." },
      { q: "Quelle est la monnaie du Japon ?", a: ["Won","Yen","Yuan","Ringgit"], c: 1, info: "Le yen est utilisé depuis 1871." },
      { q: "Combien de continents y a-t-il sur Terre ?", a: ["5","6","7","8"], c: 2, info: "Le découpage en 7 continents est le plus répandu." },
      { q: "Qui a écrit 'Roméo et Juliette' ?", a: ["Molière","Shakespeare","Victor Hugo","Dante"], c: 1, info: "Écrit vers 1594-1596 par William Shakespeare." },
      { q: "Quel organe pompe le sang dans le corps ?", a: ["Le foie","Le cœur","Le rein","Le poumon"], c: 1, info: "Le cœur bat environ 100 000 fois par jour." }
    ],
    sport: [
      { q: "Combien de joueurs par équipe au football ?", a: ["9","10","11","12"], c: 2, info: "11 joueurs dont un gardien, règle datant de 1863." },
      { q: "Quel pays a gagné le plus de Coupes du Monde ?", a: ["Allemagne","Argentine","Brésil","France"], c: 2, info: "Le Brésil compte 5 titres mondiaux." },
      { q: "Quelle couleur a la médaille du 1er aux JO ?", a: ["Bronze","Argent","Or","Platine"], c: 2, info: "La médaille d'or est en réalité surtout en argent plaqué or." },
      { q: "Surnom de Roger Federer ?", a: ["Le Maître","Le Roi","Le Maestro","L'Artiste"], c: 2, info: "Surnommé pour son jeu élégant et ses 20 titres en Grand Chelem." },
      { q: "Dans quel sport utilise-t-on un volant ?", a: ["Tennis","Squash","Badminton","Ping-pong"], c: 2, info: "Le volant peut atteindre 300 km/h au smash." },
      { q: "Combien d'étapes compte le Tour de France ?", a: ["18","19","20","21"], c: 3, info: "21 étapes sur environ 3500 km, créé en 1903." },
      { q: "Qui détient le record du 100m aux JO ?", a: ["Asafa Powell","Usain Bolt","Justin Gatlin","Tyson Gay"], c: 1, info: "9.58s à Berlin en 2009." },
      { q: "Quel pays a inventé le basketball ?", a: ["USA","Canada","Angleterre","France"], c: 0, info: "Inventé par James Naismith, un Canadien, en 1891." },
      { q: "Combien de sets pour gagner Roland-Garros (hommes) ?", a: ["2","3","4","5"], c: 1, info: "Il faut gagner 3 sets sur 5." },
      { q: "Club avec le plus de Ligues des Champions ?", a: ["Bayern Munich","Barcelone","Liverpool","Real Madrid"], c: 3, info: "Le Real Madrid en a remporté 15." },
      { q: "Dans quel sport y a-t-il un 'strike' ?", a: ["Bowling","Baseball","Cricket","Golf"], c: 0, info: "Un strike, c'est abattre les 10 quilles au premier lancer." },
      { q: "Combien de joueurs dans une équipe de rugby à XV ?", a: ["13","14","15","16"], c: 2, info: "15 joueurs, dont 8 en première ligne (le pack)." },
      { q: "Quel pays a inventé le judo ?", a: ["Chine","Corée","Japon","Thaïlande"], c: 2, info: "Créé par Jigoro Kano en 1882 au Japon." },
      { q: "Quelle distance fait un marathon ?", a: ["40,2 km","42,195 km","45 km","38 km"], c: 1, info: "Distance fixée en 1921, inspirée de la légende de Marathon." },
      { q: "Combien de points vaut un essai au rugby ?", a: ["3","5","7","10"], c: 1, info: "5 points, +2 si la transformation est réussie." }
    ],
    cinema: [
      { q: "Premier film à recevoir l'Oscar du meilleur film ?", a: ["Les Ailes","Ben-Hur","Citizen Kane","Titanic"], c: 0, info: "'Wings' a remporté le premier Oscar en 1929." },
      { q: "Qui a réalisé 'Inception' ?", a: ["James Cameron","Christopher Nolan","Steven Spielberg","Ridley Scott"], c: 1, info: "Réalisé en 2010, avec Leonardo DiCaprio." },
      { q: "Réplique 'Je serai de retour' vient de quel film ?", a: ["RoboCop","Matrix","Terminator","Predator"], c: 2, info: "Réplique culte de Schwarzenegger en 1984." },
      { q: "Film Disney avec Simba ?", a: ["Bambi","Le Livre de la Jungle","Le Roi Lion","Tarzan"], c: 2, info: "Inspiré en partie de Hamlet de Shakespeare." },
      { q: "Combien d'Oscars pour Titanic (1997) ?", a: ["9","11","13","14"], c: 1, info: "11 Oscars, à égalité avec Ben-Hur." },
      { q: "Qui joue Jack dans Titanic ?", a: ["Brad Pitt","Tom Hanks","Leonardo DiCaprio","Matt Damon"], c: 2, info: "DiCaprio avait 22 ans lors du tournage." },
      { q: "Film le plus rentable de tous les temps ?", a: ["Avatar","Avengers Endgame","Titanic","Star Wars"], c: 0, info: "Avatar (2009) : 2,9 milliards de dollars de recettes." },
      { q: "Dans quel pays est né le cinéma ?", a: ["USA","Angleterre","France","Allemagne"], c: 2, info: "Les frères Lumière, première projection en 1895." },
      { q: "Qui joue Iron Man chez Marvel ?", a: ["Chris Evans","Chris Hemsworth","Robert Downey Jr","Mark Ruffalo"], c: 2, info: "Downey Jr. a incarné Tony Stark de 2008 à 2019." },
      { q: "Quel film de Kubrick se passe dans l'espace ?", a: ["Full Metal Jacket","Shining","2001 l'Odyssée de l'Espace","Eyes Wide Shut"], c: 2, info: "Sorti en 1968, considéré comme un chef-d'œuvre." },
      { q: "Qui a réalisé 'Pulp Fiction' ?", a: ["Tarantino","Scorsese","Coppola","Lynch"], c: 0, info: "Sorti en 1994, Palme d'or à Cannes." },
      { q: "Studio derrière 'Toy Story' ?", a: ["DreamWorks","Pixar","Illumination","Disney Animation"], c: 1, info: "Premier film 100% animé en images de synthèse, 1995." },
      { q: "Acteur principal de 'Forrest Gump' ?", a: ["Tom Hanks","Tom Cruise","Brad Pitt","Kevin Costner"], c: 0, info: "Sorti en 1994, 6 Oscars." },
      { q: "Réalisateur de la trilogie 'Le Seigneur des Anneaux' ?", a: ["George Lucas","Peter Jackson","Guillermo del Toro","James Cameron"], c: 1, info: "Tournée en Nouvelle-Zélande, sortie 2001-2003." },
      { q: "Dans quel film entend-on 'Que la Force soit avec toi' ?", a: ["Star Trek","Star Wars","Dune","Interstellar"], c: 1, info: "Phrase culte de la saga Star Wars depuis 1977." }
    ],
    geo: [
      { q: "Quel est le plus grand océan ?", a: ["Atlantique","Indien","Arctique","Pacifique"], c: 3, info: "165 millions de km², plus que toutes les terres réunies." },
      { q: "Capitale du Japon ?", a: ["Osaka","Kyoto","Tokyo","Hiroshima"], c: 2, info: "37 millions d'habitants dans son aire urbaine." },
      { q: "Le plus long fleuve du monde ?", a: ["Amazone","Mississippi","Congo","Nil"], c: 3, info: "Environ 6650 km de long." },
      { q: "Sur quel continent se trouve l'Égypte ?", a: ["Asie","Europe","Afrique","Moyen-Orient"], c: 2, info: "Pays transcontinental, le Sinaï est en Asie." },
      { q: "Combien de pays compte l'Afrique ?", a: ["44","54","64","74"], c: 1, info: "Le continent avec le plus de pays reconnus." },
      { q: "La plus haute montagne du monde ?", a: ["K2","Mont Blanc","Everest","Kilimandjaro"], c: 2, info: "8849 mètres, gravi en 1953 par Hillary et Norgay." },
      { q: "Surnom de Paris ?", a: ["Cité éternelle","Ville des Lumières","Cité des Anges","Grande Pomme"], c: 1, info: "Lié aux Lumières du XVIIIe et à l'éclairage public pionnier." },
      { q: "Le pays avec le plus d'îles ?", a: ["Indonésie","Philippines","Suède","Japon"], c: 2, info: "Plus de 221 800 îles en Suède." },
      { q: "Mer entre l'Europe et l'Afrique ?", a: ["Mer Noire","Mer Rouge","Méditerranée","Mer Caspienne"], c: 2, info: "'Au milieu des terres' en latin." },
      { q: "Capitale du Canada ?", a: ["Toronto","Montréal","Vancouver","Ottawa"], c: 3, info: "Capitale depuis 1857, Toronto est la plus grande ville." },
      { q: "Désert le plus grand du monde ?", a: ["Sahara","Gobi","Antarctique","Kalahari"], c: 2, info: "Le désert antarctique est le plus grand désert (froid)." },
      { q: "Pays avec le plus d'habitants ?", a: ["Chine","Inde","USA","Indonésie"], c: 1, info: "L'Inde a dépassé la Chine en population en 2023." },
      { q: "Quelle ville est sur deux continents ?", a: ["Moscou","Istanbul","Le Caire","Athènes"], c: 1, info: "Istanbul est à cheval sur l'Europe et l'Asie." },
      { q: "Pays d'origine du tango ?", a: ["Brésil","Argentine","Espagne","Mexique"], c: 1, info: "Né à Buenos Aires fin XIXe siècle." },
      { q: "Plus grande île du monde ?", a: ["Madagascar","Bornéo","Groenland","Nouvelle-Guinée"], c: 2, info: "2,16 millions de km², recouverte à 80% de glace." }
    ],
    music: [
      { q: "Combien de cordes a une guitare classique ?", a: ["4","5","6","7"], c: 2, info: "Accordage standard : Mi La Ré Sol Si Mi." },
      { q: "Quel groupe a chanté 'Bohemian Rhapsody' ?", a: ["The Beatles","Queen","Pink Floyd","Led Zeppelin"], c: 1, info: "Sortie en 1975, écrite par Freddie Mercury." },
      { q: "Combien de touches a un piano standard ?", a: ["76","88","92","100"], c: 1, info: "52 blanches et 36 noires." },
      { q: "Qui a composé 'La Flûte enchantée' ?", a: ["Bach","Beethoven","Mozart","Chopin"], c: 2, info: "Opéra composé en 1791, l'année de sa mort." },
      { q: "Style musical né à la Nouvelle-Orléans ?", a: ["Blues","Jazz","Rock","Reggae"], c: 1, info: "Né fin XIXe / début XXe siècle." },
      { q: "Chanteuse surnommée la 'Reine de la Pop' ?", a: ["Beyoncé","Rihanna","Madonna","Lady Gaga"], c: 2, info: "Surnom acquis dans les années 1980." },
      { q: "Instrument à vent en bois avec une anche double ?", a: ["Flûte","Hautbois","Clarinette","Trompette"], c: 1, info: "L'anche double produit un son nasal caractéristique." },
      { q: "Groupe le plus vendu de tous les temps ?", a: ["The Beatles","Queen","ABBA","Michael Jackson"], c: 0, info: "Plus de 600 millions de disques vendus." },
      { q: "Genre musical né en Jamaïque ?", a: ["Salsa","Reggae","Samba","Flamenco"], c: 1, info: "Popularisé par Bob Marley dans les années 1970." },
      { q: "Qui a composé les 4 Saisons ?", a: ["Bach","Vivaldi","Mozart","Haendel"], c: 1, info: "4 concertos pour violon composés vers 1723." },
      { q: "Festival de musique le plus connu en France ?", a: ["Eurockéennes","Vieilles Charrues","Hellfest","Tous existent"], c: 3, info: "La France compte plusieurs grands festivals reconnus." },
      { q: "Instrument emblématique du flamenco ?", a: ["Violon","Guitare","Accordéon","Piano"], c: 1, info: "La guitare flamenca a un son sec et percussif." },
      { q: "Quel pays a inventé le rap moderne ?", a: ["France","Jamaïque","USA","Royaume-Uni"], c: 2, info: "Né dans le Bronx, New York, dans les années 1970." },
      { q: "Compositeur devenu sourd ?", a: ["Mozart","Beethoven","Chopin","Bach"], c: 1, info: "Beethoven a composé sa 9e Symphonie alors sourd." },
      { q: "Voix la plus aiguë chez les femmes ?", a: ["Alto","Mezzo-soprano","Soprano","Contralto"], c: 2, info: "La soprano couvre les notes les plus hautes." }
    ],
    history: [
      { q: "En quelle année a eu lieu la prise de la Bastille ?", a: ["1789","1799","1804","1815"], c: 0, info: "Le 14 juillet 1789, déclencheur de la Révolution française." },
      { q: "Qui était empereur des Français en 1810 ?", a: ["Louis XVI","Napoléon Ier","Charles X","Louis-Philippe"], c: 1, info: "Sacré empereur en 1804." },
      { q: "En quelle année le mur de Berlin est-il tombé ?", a: ["1985","1987","1989","1991"], c: 2, info: "Chute le 9 novembre 1989." },
      { q: "Quelle civilisation a construit les pyramides de Gizeh ?", a: ["Mayas","Égyptiens","Romains","Grecs"], c: 1, info: "Construites il y a environ 4500 ans." },
      { q: "Qui a découvert l'Amérique en 1492 ?", a: ["Magellan","Vasco de Gama","Christophe Colomb","Cook"], c: 2, info: "Il pensait avoir atteint les Indes." },
      { q: "En quelle année a fini la Seconde Guerre mondiale ?", a: ["1943","1944","1945","1946"], c: 2, info: "Capitulation du Japon en septembre 1945." },
      { q: "Quel roi a fait construire Versailles ?", a: ["Louis XIII","Louis XIV","Louis XV","Henri IV"], c: 1, info: "Le Roi-Soleil, château achevé vers 1682." },
      { q: "Quel empire romain a duré le plus longtemps ?", a: ["Romain d'Occident","Byzantin (Orient)","Carolingien","Ottoman"], c: 1, info: "L'Empire byzantin a duré jusqu'en 1453." },
      { q: "Qui a écrit la Déclaration d'indépendance américaine ?", a: ["Washington","Jefferson","Lincoln","Franklin"], c: 1, info: "Thomas Jefferson, en 1776." },
      { q: "Quelle reine a régné le plus longtemps en Angleterre avant 2022 ?", a: ["Victoria","Elizabeth II","Anne","Mary"], c: 1, info: "Elizabeth II a régné 70 ans, de 1952 à 2022." },
      { q: "En quelle année l'homme a-t-il marché sur la Lune ?", a: ["1965","1969","1972","1975"], c: 1, info: "Neil Armstrong, le 21 juillet 1969." },
      { q: "Quel traité a mis fin à la Première Guerre mondiale ?", a: ["Traité de Rome","Traité de Versailles","Traité de Paris","Traité de Vienne"], c: 1, info: "Signé en juin 1919." },
      { q: "Qui était Cléopâtre ?", a: ["Reine d'Égypte","Reine de Perse","Impératrice romaine","Reine de Grèce"], c: 0, info: "Dernière pharaonne d'Égypte, morte en 30 av. J.-C." },
      { q: "Quelle bataille a marqué la défaite finale de Napoléon ?", a: ["Austerlitz","Trafalgar","Waterloo","Iéna"], c: 2, info: "Le 18 juin 1815, en Belgique actuelle." },
      { q: "Quel peuple a envahi l'Empire romain au Ve siècle ?", a: ["Les Vikings","Les Huns","Les Mongols","Les Ottomans"], c: 1, info: "Attila a mené les Huns jusqu'en Europe de l'Ouest." }
    ],
    science: [
      { q: "Quelle est la formule chimique de l'eau ?", a: ["CO2","H2O","O2","NaCl"], c: 1, info: "Deux atomes d'hydrogène, un d'oxygène." },
      { q: "Quelle planète est la plus proche du soleil ?", a: ["Vénus","Mercure","Terre","Mars"], c: 1, info: "Mercure met 88 jours à faire le tour du Soleil." },
      { q: "Combien de chromosomes a l'être humain ?", a: ["23","46","48","44"], c: 1, info: "46 chromosomes, soit 23 paires." },
      { q: "Quelle force maintient les planètes en orbite ?", a: ["Le magnétisme","La gravité","L'électricité statique","La pression"], c: 1, info: "Décrite par Newton, puis par Einstein." },
      { q: "Quel gaz les plantes absorbent-elles pour la photosynthèse ?", a: ["Oxygène","Azote","CO2","Hydrogène"], c: 2, info: "Elles rejettent de l'oxygène en échange." },
      { q: "Vitesse de la lumière dans le vide ?", a: ["300 000 km/s","150 000 km/s","1 000 000 km/s","30 000 km/s"], c: 0, info: "Précisément 299 792 km/s." },
      { q: "Quel scientifique a proposé la théorie de l'évolution ?", a: ["Mendel","Darwin","Pasteur","Lamarck"], c: 1, info: "Publiée dans 'L'Origine des espèces' en 1859." },
      { q: "Combien d'os un nouveau-né a-t-il de plus qu'un adulte ?", a: ["Environ 20","Environ 64","Environ 100","Aucun"], c: 1, info: "Beaucoup fusionnent en grandissant." },
      { q: "Quel est l'organe le plus grand du corps humain ?", a: ["Le foie","Le cerveau","La peau","Le cœur"], c: 2, info: "La peau pèse environ 4 kg chez un adulte." },
      { q: "Quelle particule a une charge négative ?", a: ["Proton","Neutron","Électron","Photon"], c: 2, info: "L'électron orbite autour du noyau de l'atome." },
      { q: "Combien de temps met la Terre à faire le tour du Soleil ?", a: ["24h","30 jours","365,25 jours","12 mois exactement"], c: 2, info: "D'où l'année bissextile tous les 4 ans." },
      { q: "Quel métal est liquide à température ambiante ?", a: ["Plomb","Fer","Mercure","Zinc"], c: 2, info: "Le mercure fond à -39°C." },
      { q: "Quel est le plus grand mammifère du monde ?", a: ["Éléphant d'Afrique","Baleine bleue","Girafe","Rhinocéros"], c: 1, info: "Jusqu'à 30 mètres et 150 tonnes." },
      { q: "Qui a découvert la pénicilline ?", a: ["Pasteur","Fleming","Koch","Curie"], c: 1, info: "Alexander Fleming, en 1928, par accident." },
      { q: "Quelle est l'unité de mesure de la force ?", a: ["Le watt","Le newton","Le joule","Le pascal"], c: 1, info: "Nommé d'après Isaac Newton." }
    ],
    games: [
      { q: "Quel plombier est le héros des jeux Nintendo ?", a: ["Luigi","Mario","Wario","Yoshi"], c: 1, info: "Créé par Shigeru Miyamoto en 1981 (Donkey Kong)." },
      { q: "Dans quel jeu trouve-t-on des 'Creepers' ?", a: ["Fortnite","Minecraft","Roblox","Terraria"], c: 1, info: "Minecraft, sorti en 2011, créé par Markus Persson." },
      { q: "Quelle entreprise a créé la PlayStation ?", a: ["Microsoft","Nintendo","Sega","Sony"], c: 3, info: "Première PlayStation sortie en 1994 au Japon." },
      { q: "Dans quel jeu incarne-t-on Link ?", a: ["Final Fantasy","The Legend of Zelda","Kingdom Hearts","Fire Emblem"], c: 1, info: "Premier jeu sorti en 1986 sur NES." },
      { q: "Quel jeu a popularisé le genre 'battle royale' ?", a: ["Call of Duty","PUBG","Fortnite","Apex Legends"], c: 1, info: "PUBG a lancé la tendance en 2017." },
      { q: "Studio derrière 'The Witcher' ?", a: ["CD Projekt Red","Bethesda","Ubisoft","BioWare"], c: 0, info: "Studio polonais, série basée sur les romans de Sapkowski." },
      { q: "Quelle console a introduit la manette à deux joysticks ?", a: ["NES","Nintendo 64","PlayStation","Game Boy"], c: 1, info: "La N64 a popularisé l'analogique en 1996." },
      { q: "Dans quel jeu collecte-t-on des Pokémon ?", a: ["Digimon","Pokémon","Yo-kai Watch","Monster Hunter"], c: 1, info: "Premiers jeux sortis en 1996 sur Game Boy." },
      { q: "Quel jeu vidéo est le plus vendu de l'histoire ?", a: ["GTA V","Minecraft","Tetris","Wii Sports"], c: 1, info: "Plus de 300 millions d'exemplaires vendus." },
      { q: "Dans quelle ville se déroule GTA V ?", a: ["Liberty City","Vice City","Los Santos","San Fierro"], c: 2, info: "Los Santos, inspirée de Los Angeles." },
      { q: "Quel jeu oppose des champions dans une 'Faille' ?", a: ["Dota 2","League of Legends","Valorant","Overwatch"], c: 1, info: "League of Legends, sorti en 2009." },
      { q: "Quelle entreprise a créé Fortnite ?", a: ["Valve","Epic Games","Riot Games","Activision"], c: 1, info: "Epic Games, sorti en 2017." },
      { q: "Premier jeu vidéo de l'histoire (selon les historiens) ?", a: ["Pong","Tennis for Two","Space Invaders","Pac-Man"], c: 1, info: "Créé en 1958 par William Higinbotham." },
      { q: "Dans quel jeu incarne-t-on un agent dans Hyrule ?", a: ["Aucun, Hyrule c'est Zelda","Metroid","Star Fox","Splatoon"], c: 0, info: "Hyrule est le royaume fictif de la saga Zelda." },
      { q: "Quel personnage est la mascotte de Sega ?", a: ["Mario","Sonic","Pac-Man","Kirby"], c: 1, info: "Sonic the Hedgehog, créé en 1991." }
    ],
    series: [
      { q: "Dans quelle ville se passe 'Friends' ?", a: ["Los Angeles","Chicago","New York","Boston"], c: 2, info: "Diffusée de 1994 à 2004, 10 saisons." },
      { q: "Combien de saisons compte 'Breaking Bad' ?", a: ["3","4","5","6"], c: 2, info: "Diffusée de 2008 à 2013." },
      { q: "Quel est le nom de famille des héros de 'Game of Thrones' au nord ?", a: ["Lannister","Targaryen","Stark","Baratheon"], c: 2, info: "La maison Stark règne sur le Nord, à Winterfell." },
      { q: "Dans quelle série trouve-t-on le Dr House ?", a: ["Grey's Anatomy","Dr House","Urgences","Scrubs"], c: 1, info: "Série diffusée de 2004 à 2012." },
      { q: "Quel monstre apparaît dans 'Stranger Things' ?", a: ["Le Slender Man","Le Demogorgon","Le Joker","Le Predator"], c: 1, info: "Nommé d'après une créature de Donjons & Dragons." },
      { q: "Combien d'amis composent le groupe dans 'Friends' ?", a: ["4","5","6","7"], c: 2, info: "Ross, Rachel, Monica, Chandler, Joey, Phoebe." },
      { q: "Quelle série suit une famille de mafieux dans le New Jersey ?", a: ["Breaking Bad","Les Soprano","Narcos","Peaky Blinders"], c: 1, info: "Diffusée de 1999 à 2007, culte du genre." },
      { q: "Dans quel pays se passe 'Money Heist' (La Casa de Papel) ?", a: ["Italie","Portugal","Espagne","Mexique"], c: 2, info: "Série espagnole diffusée à partir de 2017." },
      { q: "Quel est le métier de Walter White dans 'Breaking Bad' ?", a: ["Médecin","Avocat","Professeur de chimie","Ingénieur"], c: 2, info: "Il devient producteur de méthamphétamine." },
      { q: "Combien de maisons royales dans 'Game of Thrones' (principales) ?", a: ["4","5","6","7"], c: 3, info: "7 grandes maisons + le Trône de Fer en jeu." },
      { q: "Quelle série se déroule dans un bureau de papeterie ?", a: ["The Office","Parks and Recreation","30 Rock","Community"], c: 0, info: "Version US adaptée de la série britannique." },
      { q: "Dans quelle ville se passe 'Sherlock' (BBC) ?", a: ["New York","Londres","Edimbourg","Dublin"], c: 1, info: "Adaptation moderne de Sherlock Holmes, depuis 2010." },
      { q: "Quel acteur joue Eleven dans 'Stranger Things' ?", a: ["Millie Bobby Brown","Sadie Sink","Natalia Dyer","Maya Hawke"], c: 0, info: "Elle avait 12 ans au début du tournage en 2015." },
      { q: "Quelle série met en scène un chimiste devenu narcotrafiquant ?", a: ["Narcos","Breaking Bad","Ozark","Better Call Saul"], c: 1, info: "Considérée comme une des meilleures séries de l'histoire." },
      { q: "Dans quelle série apparaît le personnage de Don Draper ?", a: ["Suits","Mad Men","Billions","House of Cards"], c: 1, info: "Série sur la publicité à New York dans les années 60." }
    ],
    animals: [
      { q: "Quel est le plus grand animal terrestre ?", a: ["Girafe","Éléphant d'Afrique","Rhinocéros","Hippopotame"], c: 1, info: "Jusqu'à 6 tonnes et 4 mètres au garrot." },
      { q: "Combien de cœurs a une pieuvre ?", a: ["1","2","3","4"], c: 2, info: "Trois cœurs : deux pour les branchies, un pour le corps." },
      { q: "Quel animal dort le plus longtemps par jour ?", a: ["Chat","Koala","Paresseux","Lion"], c: 1, info: "Le koala dort jusqu'à 20 heures par jour." },
      { q: "Quelle est la vitesse de pointe du guépard ?", a: ["80 km/h","100 km/h","120 km/h","70 km/h"], c: 1, info: "Le guépard atteint environ 100-110 km/h en sprint." },
      { q: "Quel oiseau ne peut pas voler ?", a: ["Aigle","Pingouin","Manchot","Faucon"], c: 2, info: "Les manchots ont des ailes adaptées à la nage." },
      { q: "Combien de pattes a une araignée ?", a: ["6","8","10","12"], c: 1, info: "8 pattes, ce qui en fait un arachnide, pas un insecte." },
      { q: "Quel animal change de couleur pour se camoufler ?", a: ["Caméléon","Iguane","Salamandre","Tous les lézards"], c: 0, info: "Le caméléon change aussi de couleur selon son humeur." },
      { q: "Quel est le plus rapide animal marin ?", a: ["Requin","Espadon","Dauphin","Orque"], c: 1, info: "L'espadon peut atteindre 110 km/h." },
      { q: "Combien de temps vit une tortue géante des Galápagos ?", a: ["50 ans","100 ans","plus de 150 ans","30 ans"], c: 2, info: "Certaines ont dépassé 170 ans." },
      { q: "Quel animal a la meilleure mémoire selon les études ?", a: ["Dauphin","Éléphant","Corbeau","Chimpanzé"], c: 1, info: "Les éléphants se souviennent d'individus pendant des décennies." },
      { q: "Quel est le seul mammifère capable de voler ?", a: ["Écureuil volant","Chauve-souris","Opossum","Lémurien"], c: 1, info: "La chauve-souris est le seul vrai mammifère volant." },
      { q: "Quel animal produit du miel ?", a: ["Guêpe","Bourdon","Abeille","Fourmi"], c: 2, info: "Les abeilles transforment le nectar en miel." },
      { q: "Quel est le plus grand poisson du monde ?", a: ["Requin blanc","Requin baleine","Thon rouge","Espadon"], c: 1, info: "Le requin-baleine peut mesurer 18 mètres, mais il est inoffensif." },
      { q: "Quel animal a un cri plus fort qu'un avion au décollage ?", a: ["Lion","Éléphant","Baleine bleue","Hyène"], c: 2, info: "Le chant de la baleine bleue peut dépasser 180 décibels." },
      { q: "Combien de cœurs a un vers de terre ?", a: ["1","3","5","10"], c: 2, info: "5 paires de structures qui pompent le sang, soit 5 'cœurs'." }
    ]
  },

  en: {
    culture: [
      { q: "What is the capital of Australia?", a: ["Sydney","Melbourne","Canberra","Brisbane"], c: 2, info: "Many think it's Sydney, but Canberra has been the capital since 1927." },
      { q: "How many planets are in our solar system?", a: ["7","8","9","10"], c: 1, info: "Pluto was reclassified as a dwarf planet in 2006." },
      { q: "Who painted the Mona Lisa?", a: ["Michelangelo","Raphael","Leonardo da Vinci","Botticelli"], c: 2, info: "Painted between 1503 and 1519, now in the Louvre." },
      { q: "What year did World War I begin?", a: ["1912","1914","1916","1918"], c: 1, info: "Triggered by the assassination of Archduke Franz Ferdinand." },
      { q: "What is the chemical symbol for gold?", a: ["Ag","Al","Au","Or"], c: 2, info: "Au comes from the Latin 'Aurum'." },
      { q: "Which country has the largest land area?", a: ["Canada","China","USA","Russia"], c: 3, info: "Russia covers 17.1 million km²." },
      { q: "How many bones does an adult human have?", a: ["186","206","226","246"], c: 1, info: "Babies are born with about 270 bones." },
      { q: "What is the most spoken native language?", a: ["English","Spanish","Mandarin","Hindi"], c: 2, info: "Mandarin has 1.1 billion native speakers." },
      { q: "Who formulated the theory of relativity?", a: ["Newton","Tesla","Curie","Einstein"], c: 3, info: "Special relativity in 1905, general in 1915." },
      { q: "Where is Machu Picchu located?", a: ["Bolivia","Mexico","Peru","Colombia"], c: 2, info: "Inca city at 2430m altitude, built around 1450." },
      { q: "What is the smallest country in the world?", a: ["Monaco","Vatican City","Nauru","Malta"], c: 1, info: "Vatican City covers about 0.49 km²." },
      { q: "What is the currency of Japan?", a: ["Won","Yen","Yuan","Ringgit"], c: 1, info: "The yen has been used since 1871." },
      { q: "How many continents are there?", a: ["5","6","7","8"], c: 2, info: "The 7-continent model is the most common." },
      { q: "Who wrote 'Romeo and Juliet'?", a: ["Molière","Shakespeare","Victor Hugo","Dante"], c: 1, info: "Written around 1594-1596 by William Shakespeare." },
      { q: "Which organ pumps blood through the body?", a: ["Liver","Heart","Kidney","Lung"], c: 1, info: "The heart beats about 100,000 times a day." }
    ],
    sport: [
      { q: "How many players per team in football (soccer)?", a: ["9","10","11","12"], c: 2, info: "11 players including a goalkeeper, rule dating to 1863." },
      { q: "Which country has won the most World Cups?", a: ["Germany","Argentina","Brazil","France"], c: 2, info: "Brazil holds 5 World Cup titles." },
      { q: "What color is the 1st place Olympic medal?", a: ["Bronze","Silver","Gold","Platinum"], c: 2, info: "Gold medals are mostly silver, gold-plated." },
      { q: "Roger Federer's nickname?", a: ["The Master","The King","The Maestro","The Artist"], c: 2, info: "Named for his elegant play and 20 Grand Slam titles." },
      { q: "Which sport uses a shuttlecock?", a: ["Tennis","Squash","Badminton","Table tennis"], c: 2, info: "The shuttlecock can reach 300 km/h on a smash." },
      { q: "How many stages does the Tour de France have?", a: ["18","19","20","21"], c: 3, info: "21 stages over about 3500 km, started in 1903." },
      { q: "Who holds the Olympic 100m record?", a: ["Asafa Powell","Usain Bolt","Justin Gatlin","Tyson Gay"], c: 1, info: "9.58s in Berlin in 2009." },
      { q: "Which country invented basketball?", a: ["USA","Canada","England","France"], c: 0, info: "Invented by James Naismith, a Canadian, in 1891 in the US." },
      { q: "How many sets to win Wimbledon (men)?", a: ["2","3","4","5"], c: 1, info: "You need to win 3 sets out of 5." },
      { q: "Club with most Champions League titles?", a: ["Bayern Munich","Barcelona","Liverpool","Real Madrid"], c: 3, info: "Real Madrid has won it 15 times." },
      { q: "Which sport features a 'strike'?", a: ["Bowling","Baseball","Cricket","Golf"], c: 0, info: "A strike means knocking down all 10 pins on the first throw." },
      { q: "How many players in a rugby union team?", a: ["13","14","15","16"], c: 2, info: "15 players, 8 of them forming the pack." },
      { q: "Which country invented judo?", a: ["China","Korea","Japan","Thailand"], c: 2, info: "Created by Jigoro Kano in 1882 in Japan." },
      { q: "How long is a marathon?", a: ["40.2 km","42.195 km","45 km","38 km"], c: 1, info: "Distance fixed in 1921, based on the Marathon legend." },
      { q: "How many points is a rugby try worth?", a: ["3","5","7","10"], c: 1, info: "5 points, +2 if the conversion is successful." }
    ],
    cinema: [
      { q: "First film to win Best Picture Oscar?", a: ["Wings","Ben-Hur","Citizen Kane","Titanic"], c: 0, info: "'Wings' won the first Best Picture Oscar in 1929." },
      { q: "Who directed 'Inception'?", a: ["James Cameron","Christopher Nolan","Steven Spielberg","Ridley Scott"], c: 1, info: "Released in 2010, starring Leonardo DiCaprio." },
      { q: "'I'll be back' is from which film?", a: ["RoboCop","The Matrix","Terminator","Predator"], c: 2, info: "Iconic Schwarzenegger line from 1984." },
      { q: "Which Disney film features Simba?", a: ["Bambi","The Jungle Book","The Lion King","Tarzan"], c: 2, info: "Partly inspired by Shakespeare's Hamlet." },
      { q: "How many Oscars did Titanic (1997) win?", a: ["9","11","13","14"], c: 1, info: "11 Oscars, tied with Ben-Hur." },
      { q: "Who plays Jack in Titanic?", a: ["Brad Pitt","Tom Hanks","Leonardo DiCaprio","Matt Damon"], c: 2, info: "DiCaprio was 22 during filming." },
      { q: "Highest-grossing film of all time?", a: ["Avatar","Avengers Endgame","Titanic","Star Wars"], c: 0, info: "Avatar (2009) earned $2.9 billion." },
      { q: "In which country was cinema born?", a: ["USA","England","France","Germany"], c: 2, info: "The Lumière brothers, first screening in 1895." },
      { q: "Who plays Iron Man in Marvel films?", a: ["Chris Evans","Chris Hemsworth","Robert Downey Jr","Mark Ruffalo"], c: 2, info: "Downey Jr. played Tony Stark from 2008 to 2019." },
      { q: "Which Kubrick film is set in space?", a: ["Full Metal Jacket","The Shining","2001: A Space Odyssey","Eyes Wide Shut"], c: 2, info: "Released in 1968, considered a masterpiece." },
      { q: "Who directed 'Pulp Fiction'?", a: ["Tarantino","Scorsese","Coppola","Lynch"], c: 0, info: "Released in 1994, won the Palme d'Or at Cannes." },
      { q: "Studio behind 'Toy Story'?", a: ["DreamWorks","Pixar","Illumination","Disney Animation"], c: 1, info: "First fully CGI feature film, 1995." },
      { q: "Lead actor in 'Forrest Gump'?", a: ["Tom Hanks","Tom Cruise","Brad Pitt","Kevin Costner"], c: 0, info: "Released in 1994, won 6 Oscars." },
      { q: "Director of 'The Lord of the Rings' trilogy?", a: ["George Lucas","Peter Jackson","Guillermo del Toro","James Cameron"], c: 1, info: "Filmed in New Zealand, released 2001-2003." },
      { q: "In which film do you hear 'May the Force be with you'?", a: ["Star Trek","Star Wars","Dune","Interstellar"], c: 1, info: "Iconic line from the Star Wars saga since 1977." }
    ],
    geo: [
      { q: "What is the largest ocean?", a: ["Atlantic","Indian","Arctic","Pacific"], c: 3, info: "165 million km², more than all land combined." },
      { q: "Capital of Japan?", a: ["Osaka","Kyoto","Tokyo","Hiroshima"], c: 2, info: "37 million people in its metro area." },
      { q: "The longest river in the world?", a: ["Amazon","Mississippi","Congo","Nile"], c: 3, info: "About 6650 km long." },
      { q: "Which continent is Egypt on?", a: ["Asia","Europe","Africa","Middle East"], c: 2, info: "A transcontinental country; Sinai is in Asia." },
      { q: "How many countries are in Africa?", a: ["44","54","64","74"], c: 1, info: "The continent with the most recognized countries." },
      { q: "The tallest mountain in the world?", a: ["K2","Mont Blanc","Everest","Kilimanjaro"], c: 2, info: "8849 meters, first climbed in 1953 by Hillary and Norgay." },
      { q: "Paris's nickname?", a: ["Eternal City","City of Light","City of Angels","Big Apple"], c: 1, info: "Linked to the Enlightenment and early street lighting." },
      { q: "Country with the most islands?", a: ["Indonesia","Philippines","Sweden","Japan"], c: 2, info: "Sweden has over 221,800 islands." },
      { q: "Sea between Europe and Africa?", a: ["Black Sea","Red Sea","Mediterranean","Caspian Sea"], c: 2, info: "Latin for 'in the middle of the land'." },
      { q: "Capital of Canada?", a: ["Toronto","Montreal","Vancouver","Ottawa"], c: 3, info: "Capital since 1857; Toronto is the largest city." },
      { q: "The largest desert in the world?", a: ["Sahara","Gobi","Antarctic","Kalahari"], c: 2, info: "The Antarctic desert is the largest (a cold desert)." },
      { q: "The most populated country?", a: ["China","India","USA","Indonesia"], c: 1, info: "India overtook China in population in 2023." },
      { q: "Which city sits on two continents?", a: ["Moscow","Istanbul","Cairo","Athens"], c: 1, info: "Istanbul straddles Europe and Asia." },
      { q: "Country of origin of the tango?", a: ["Brazil","Argentina","Spain","Mexico"], c: 1, info: "Born in Buenos Aires in the late 19th century." },
      { q: "The largest island in the world?", a: ["Madagascar","Borneo","Greenland","New Guinea"], c: 2, info: "2.16 million km², 80% covered in ice." }
    ],
    music: [
      { q: "How many strings does a classical guitar have?", a: ["4","5","6","7"], c: 2, info: "Standard tuning: E A D G B E." },
      { q: "Which band sang 'Bohemian Rhapsody'?", a: ["The Beatles","Queen","Pink Floyd","Led Zeppelin"], c: 1, info: "Released in 1975, written by Freddie Mercury." },
      { q: "How many keys does a standard piano have?", a: ["76","88","92","100"], c: 1, info: "52 white keys and 36 black keys." },
      { q: "Who composed 'The Magic Flute'?", a: ["Bach","Beethoven","Mozart","Chopin"], c: 2, info: "Opera composed in 1791, the year of his death." },
      { q: "Musical style born in New Orleans?", a: ["Blues","Jazz","Rock","Reggae"], c: 1, info: "Born in the late 19th / early 20th century." },
      { q: "Singer nicknamed the 'Queen of Pop'?", a: ["Beyoncé","Rihanna","Madonna","Lady Gaga"], c: 2, info: "Nickname earned in the 1980s." },
      { q: "Woodwind instrument with a double reed?", a: ["Flute","Oboe","Clarinet","Trumpet"], c: 1, info: "The double reed gives it a nasal tone." },
      { q: "Best-selling band of all time?", a: ["The Beatles","Queen","ABBA","Michael Jackson"], c: 0, info: "Over 600 million records sold." },
      { q: "Musical genre born in Jamaica?", a: ["Salsa","Reggae","Samba","Flamenco"], c: 1, info: "Popularized by Bob Marley in the 1970s." },
      { q: "Who composed 'The Four Seasons'?", a: ["Bach","Vivaldi","Mozart","Handel"], c: 1, info: "4 violin concertos composed around 1723." },
      { q: "Which country pioneered modern jazz?", a: ["France","Jamaica","USA","UK"], c: 2, info: "Jazz developed mainly in the United States." },
      { q: "Instrument central to flamenco?", a: ["Violin","Guitar","Accordion","Piano"], c: 1, info: "The flamenco guitar has a dry, percussive sound." },
      { q: "Which country birthed modern rap?", a: ["France","Jamaica","USA","UK"], c: 2, info: "Born in the Bronx, New York, in the 1970s." },
      { q: "Composer who went deaf?", a: ["Mozart","Beethoven","Chopin","Bach"], c: 1, info: "Beethoven composed his 9th Symphony while deaf." },
      { q: "Highest female singing voice?", a: ["Alto","Mezzo-soprano","Soprano","Contralto"], c: 2, info: "Soprano covers the highest notes." }
    ],
    history: [
      { q: "What year was the storming of the Bastille?", a: ["1789","1799","1804","1815"], c: 0, info: "July 14, 1789, sparked the French Revolution." },
      { q: "Who was Emperor of the French in 1810?", a: ["Louis XVI","Napoleon I","Charles X","Louis-Philippe"], c: 1, info: "Crowned emperor in 1804." },
      { q: "What year did the Berlin Wall fall?", a: ["1985","1987","1989","1991"], c: 2, info: "Fell on November 9, 1989." },
      { q: "Which civilization built the Pyramids of Giza?", a: ["Maya","Egyptians","Romans","Greeks"], c: 1, info: "Built about 4500 years ago." },
      { q: "Who discovered America in 1492?", a: ["Magellan","Vasco da Gama","Christopher Columbus","Cook"], c: 2, info: "He believed he had reached the Indies." },
      { q: "What year did World War II end?", a: ["1943","1944","1945","1946"], c: 2, info: "Japan surrendered in September 1945." },
      { q: "Which king built the Palace of Versailles?", a: ["Louis XIII","Louis XIV","Louis XV","Henri IV"], c: 1, info: "The Sun King; the palace was finished around 1682." },
      { q: "Which Roman empire lasted the longest?", a: ["Western Roman","Byzantine (Eastern)","Carolingian","Ottoman"], c: 1, info: "The Byzantine Empire lasted until 1453." },
      { q: "Who wrote the US Declaration of Independence?", a: ["Washington","Jefferson","Lincoln","Franklin"], c: 1, info: "Thomas Jefferson, in 1776." },
      { q: "Longest-reigning British monarch before 2022?", a: ["Victoria","Elizabeth II","Anne","Mary"], c: 1, info: "Elizabeth II reigned 70 years, 1952 to 2022." },
      { q: "What year did humans first walk on the Moon?", a: ["1965","1969","1972","1975"], c: 1, info: "Neil Armstrong, on July 21, 1969." },
      { q: "Which treaty ended World War I?", a: ["Treaty of Rome","Treaty of Versailles","Treaty of Paris","Treaty of Vienna"], c: 1, info: "Signed in June 1919." },
      { q: "Who was Cleopatra?", a: ["Queen of Egypt","Queen of Persia","Roman Empress","Queen of Greece"], c: 0, info: "Last pharaoh of Egypt, died in 30 BCE." },
      { q: "Which battle marked Napoleon's final defeat?", a: ["Austerlitz","Trafalgar","Waterloo","Jena"], c: 2, info: "On June 18, 1815, in present-day Belgium." },
      { q: "Which people invaded the Roman Empire in the 5th century?", a: ["The Vikings","The Huns","The Mongols","The Ottomans"], c: 1, info: "Attila led the Huns into Western Europe." }
    ],
    science: [
      { q: "What is the chemical formula for water?", a: ["CO2","H2O","O2","NaCl"], c: 1, info: "Two hydrogen atoms, one oxygen atom." },
      { q: "Which planet is closest to the sun?", a: ["Venus","Mercury","Earth","Mars"], c: 1, info: "Mercury orbits the Sun in 88 days." },
      { q: "How many chromosomes do humans have?", a: ["23","46","48","44"], c: 1, info: "46 chromosomes, in 23 pairs." },
      { q: "What force keeps planets in orbit?", a: ["Magnetism","Gravity","Static electricity","Pressure"], c: 1, info: "Described by Newton, later refined by Einstein." },
      { q: "Which gas do plants absorb for photosynthesis?", a: ["Oxygen","Nitrogen","CO2","Hydrogen"], c: 2, info: "They release oxygen in exchange." },
      { q: "Speed of light in a vacuum?", a: ["300,000 km/s","150,000 km/s","1,000,000 km/s","30,000 km/s"], c: 0, info: "Precisely 299,792 km/s." },
      { q: "Which scientist proposed the theory of evolution?", a: ["Mendel","Darwin","Pasteur","Lamarck"], c: 1, info: "Published in 'On the Origin of Species' in 1859." },
      { q: "How many more bones does a newborn have than an adult?", a: ["About 20","About 64","About 100","None"], c: 1, info: "Many fuse together while growing." },
      { q: "What is the largest organ in the human body?", a: ["Liver","Brain","Skin","Heart"], c: 2, info: "Skin weighs about 4 kg in an adult." },
      { q: "Which particle has a negative charge?", a: ["Proton","Neutron","Electron","Photon"], c: 2, info: "Electrons orbit the atom's nucleus." },
      { q: "How long does Earth take to orbit the Sun?", a: ["24h","30 days","365.25 days","Exactly 12 months"], c: 2, info: "Hence a leap year every 4 years." },
      { q: "Which metal is liquid at room temperature?", a: ["Lead","Iron","Mercury","Zinc"], c: 2, info: "Mercury melts at -39°C." },
      { q: "What is the largest mammal in the world?", a: ["African elephant","Blue whale","Giraffe","Rhinoceros"], c: 1, info: "Up to 30 meters long and 150 tons." },
      { q: "Who discovered penicillin?", a: ["Pasteur","Fleming","Koch","Curie"], c: 1, info: "Alexander Fleming, in 1928, by accident." },
      { q: "What is the unit of measurement for force?", a: ["Watt","Newton","Joule","Pascal"], c: 1, info: "Named after Isaac Newton." }
    ],
    games: [
      { q: "Which plumber is Nintendo's main hero?", a: ["Luigi","Mario","Wario","Yoshi"], c: 1, info: "Created by Shigeru Miyamoto in 1981 (Donkey Kong)." },
      { q: "Which game features 'Creepers'?", a: ["Fortnite","Minecraft","Roblox","Terraria"], c: 1, info: "Minecraft, released 2011, created by Markus Persson." },
      { q: "Which company made the PlayStation?", a: ["Microsoft","Nintendo","Sega","Sony"], c: 3, info: "First PlayStation released in Japan in 1994." },
      { q: "Which game do you play as Link in?", a: ["Final Fantasy","The Legend of Zelda","Kingdom Hearts","Fire Emblem"], c: 1, info: "First game released in 1986 on the NES." },
      { q: "Which game popularized the battle royale genre?", a: ["Call of Duty","PUBG","Fortnite","Apex Legends"], c: 1, info: "PUBG started the trend in 2017." },
      { q: "Studio behind 'The Witcher'?", a: ["CD Projekt Red","Bethesda","Ubisoft","BioWare"], c: 0, info: "Polish studio, based on Sapkowski's novels." },
      { q: "Which console popularized the analog joystick?", a: ["NES","Nintendo 64","PlayStation","Game Boy"], c: 1, info: "The N64 popularized analog sticks in 1996." },
      { q: "Which game involves collecting Pokémon?", a: ["Digimon","Pokémon","Yo-kai Watch","Monster Hunter"], c: 1, info: "First games released in 1996 on Game Boy." },
      { q: "Best-selling video game of all time?", a: ["GTA V","Minecraft","Tetris","Wii Sports"], c: 1, info: "Over 300 million copies sold." },
      { q: "Which city is GTA V set in?", a: ["Liberty City","Vice City","Los Santos","San Fierro"], c: 2, info: "Los Santos, inspired by Los Angeles." },
      { q: "Which game features champions fighting in 'The Rift'?", a: ["Dota 2","League of Legends","Valorant","Overwatch"], c: 1, info: "League of Legends, released in 2009." },
      { q: "Which company created Fortnite?", a: ["Valve","Epic Games","Riot Games","Activision"], c: 1, info: "Epic Games, released in 2017." },
      { q: "What's considered the first video game ever?", a: ["Pong","Tennis for Two","Space Invaders","Pac-Man"], c: 1, info: "Created in 1958 by William Higinbotham." },
      { q: "Where does the Legend of Zelda series take place?", a: ["Hyrule","Mushroom Kingdom","Hyrule, yes","Termina"], c: 2, info: "Hyrule is the fictional kingdom of the Zelda saga." },
      { q: "Which character is Sega's mascot?", a: ["Mario","Sonic","Pac-Man","Kirby"], c: 1, info: "Sonic the Hedgehog, created in 1991." }
    ],
    series: [
      { q: "Which city is 'Friends' set in?", a: ["Los Angeles","Chicago","New York","Boston"], c: 2, info: "Aired from 1994 to 2004, 10 seasons." },
      { q: "How many seasons does 'Breaking Bad' have?", a: ["3","4","5","6"], c: 2, info: "Aired from 2008 to 2013." },
      { q: "Which house rules the North in 'Game of Thrones'?", a: ["Lannister","Targaryen","Stark","Baratheon"], c: 2, info: "House Stark rules the North, from Winterfell." },
      { q: "Which show features Dr. House?", a: ["Grey's Anatomy","House M.D.","ER","Scrubs"], c: 1, info: "Aired from 2004 to 2012." },
      { q: "Which monster appears in 'Stranger Things'?", a: ["The Slender Man","The Demogorgon","The Joker","The Predator"], c: 1, info: "Named after a Dungeons & Dragons creature." },
      { q: "How many friends are in the main 'Friends' group?", a: ["4","5","6","7"], c: 2, info: "Ross, Rachel, Monica, Chandler, Joey, Phoebe." },
      { q: "Which show follows a mob family in New Jersey?", a: ["Breaking Bad","The Sopranos","Narcos","Peaky Blinders"], c: 1, info: "Aired from 1999 to 2007, a genre classic." },
      { q: "Which country is 'Money Heist' set in?", a: ["Italy","Portugal","Spain","Mexico"], c: 2, info: "Spanish series, aired from 2017." },
      { q: "What is Walter White's job in 'Breaking Bad'?", a: ["Doctor","Lawyer","Chemistry teacher","Engineer"], c: 2, info: "He becomes a methamphetamine producer." },
      { q: "How many main royal houses in 'Game of Thrones'?", a: ["4","5","6","7"], c: 3, info: "7 great houses competing for the Iron Throne." },
      { q: "Which show is set in a paper company office?", a: ["The Office","Parks and Recreation","30 Rock","Community"], c: 0, info: "US version adapted from the British original." },
      { q: "Which city is 'Sherlock' (BBC) set in?", a: ["New York","London","Edinburgh","Dublin"], c: 1, info: "Modern adaptation of Sherlock Holmes, since 2010." },
      { q: "Which actress plays Eleven in 'Stranger Things'?", a: ["Millie Bobby Brown","Sadie Sink","Natalia Dyer","Maya Hawke"], c: 0, info: "She was 12 when filming began in 2015." },
      { q: "Which show features a chemistry teacher turned drug producer?", a: ["Narcos","Breaking Bad","Ozark","Better Call Saul"], c: 1, info: "Widely considered one of the best TV shows ever." },
      { q: "Which show features Don Draper?", a: ["Suits","Mad Men","Billions","House of Cards"], c: 1, info: "Series about 1960s New York advertising." }
    ],
    animals: [
      { q: "What is the largest land animal?", a: ["Giraffe","African elephant","Rhinoceros","Hippopotamus"], c: 1, info: "Up to 6 tons and 4 meters at the shoulder." },
      { q: "How many hearts does an octopus have?", a: ["1","2","3","4"], c: 2, info: "Three hearts: two for the gills, one for the body." },
      { q: "Which animal sleeps the longest per day?", a: ["Cat","Koala","Sloth","Lion"], c: 1, info: "Koalas sleep up to 20 hours a day." },
      { q: "What's the cheetah's top speed?", a: ["80 km/h","100 km/h","120 km/h","70 km/h"], c: 1, info: "Cheetahs reach about 100-110 km/h sprinting." },
      { q: "Which bird cannot fly?", a: ["Eagle","Penguin","Penguin","Falcon"], c: 1, info: "Penguins have flippers adapted for swimming." },
      { q: "How many legs does a spider have?", a: ["6","8","10","12"], c: 1, info: "8 legs, making it an arachnid, not an insect." },
      { q: "Which animal changes color to camouflage?", a: ["Chameleon","Iguana","Salamander","All lizards"], c: 0, info: "Chameleons also change color based on mood." },
      { q: "What's the fastest marine animal?", a: ["Shark","Swordfish","Dolphin","Orca"], c: 1, info: "Swordfish can reach 110 km/h." },
      { q: "How long can a Galápagos giant tortoise live?", a: ["50 years","100 years","over 150 years","30 years"], c: 2, info: "Some have lived past 170 years." },
      { q: "Which animal has the best long-term memory?", a: ["Dolphin","Elephant","Crow","Chimpanzee"], c: 1, info: "Elephants remember individuals for decades." },
      { q: "What's the only mammal capable of true flight?", a: ["Flying squirrel","Bat","Opossum","Lemur"], c: 1, info: "Bats are the only mammals capable of sustained flight." },
      { q: "Which animal produces honey?", a: ["Wasp","Bumblebee","Honeybee","Ant"], c: 2, info: "Honeybees turn nectar into honey." },
      { q: "What's the largest fish in the world?", a: ["Great white shark","Whale shark","Bluefin tuna","Swordfish"], c: 1, info: "Whale sharks can reach 18 meters but are harmless." },
      { q: "Which animal's call is louder than a jet takeoff?", a: ["Lion","Elephant","Blue whale","Hyena"], c: 2, info: "Blue whale calls can exceed 180 decibels." },
      { q: "How many hearts does an earthworm have?", a: ["1","3","5","10"], c: 2, info: "5 pairs of pumping structures, often called 5 'hearts'." }
    ]
  }
};
